export enum SpecializationField {
  POWERLIFTING = 'POWERLIFTING',
  CROSSFIT = 'CROSSFIT',
  BODYBUILDING = 'BODYBUILDING',
  WEIGHT_LOSS = 'WEIGHT_LOSS',
  STRENGTH_TRAINING = 'STRENGTH_TRAINING',
  CARDIO = 'CARDIO',
  YOGA = 'YOGA',
  PILATES = 'PILATES',
  SPORTS_PERFORMANCE = 'SPORTS_PERFORMANCE',
  REHABILITATION = 'REHABILITATION',
  NUTRITION = 'NUTRITION',
}

export enum CommunicationMethod {
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  TEXT_MESSAGE = 'TEXT_MESSAGE',
  IN_APP_MESSAGING = 'IN_APP_MESSAGING',
}
